#servlet配置
server:
  port: 8000 #指定端口
  servlet:
    context-path: /group #指定前缀
  tomcat:
    uri-encoding: UTF-8

#Redis配置
spring:
  #Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 47.92.23.43  # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: ycbus19931011 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

  #HTTP配置
  http:
    encoding:
      charset: UTF-8
      enabled: true

  #数据库配置
  datasource:
    url: jdbc:mysql://39.108.235.163:3306/group_purchase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Jhl090201.
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    date-format: yyyy-MM-ss HH:mm:ss
    time-zone: GMT+8

  #文件上传的大小拦截
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

##Mybatis配置
mybatis:
  type-aliases-package: com.group.shop.entity
  mapper-locations: classpath:mapper/*.xml

#分页设置
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#打印mybatis的Sql语句
logging:
  level:
    com.example.strobe.mapper: trace

